<?php
$editingShop=null; $editingProduct=null;
foreach ($data['shops'] as $row) if ($row['id']===($_GET['edit_shop']??'')) $editingShop=$row;
foreach ($data['products'] as $row) if ($row['id']===($_GET['edit_product']??'')) $editingProduct=$row;
$posted=$_SERVER['REQUEST_METHOD']==='POST'?$_POST:[];
$shopValues=($posted['action']??'')==='shop'?$posted:($editingShop??[]);
$productValues=$editingProduct??[];
if ($editingProduct) {
    $v=$children('variants',$editingProduct['id'])[0]??[]; $m=$children('media',$editingProduct['id'])[0]??[];
    $productValues=array_merge($productValues,$v,$m,['id'=>$editingProduct['id'],'revision'=>$editingProduct['revision'],'variant_name'=>$v['name']??'','name'=>$editingProduct['name']]);
    foreach ($children('offers',$editingProduct['id']) as $o) { $k=$o['kind']; $productValues[$k.'_enabled']='yes'; $productValues[$k.'_price']=$o['price_vnd']??''; $productValues[$k.'_unit']=$o['unit']; $productValues[$k.'_terms']=$o['terms']; if ($k==='rent') $productValues['rent_deposit']=$o['deposit_vnd']??''; }
    $productValues['display_consent']='yes'; $productValues['ai_consent']=in_array($m['ai_permission']??'',['requested','granted'],true)?'yes':'';
}
if (($posted['action']??'')==='product') $productValues=$posted;
$field=static function(string $key,string $label,array $values,int $max,bool $required=false,string $type='text') use($escape):void { ?>
    <label><?=$label?><input type="<?=$type?>" name="<?=$key?>" value="<?=$escape($values[$key]??'')?>" maxlength="<?=$max?>" <?=$required?'required':''?> <?=$type==='url'?'placeholder="https://…"':''?>></label>
<?php };
?>
<section class="network-panel"><h2>Hồ sơ của bạn</h2>
<?php if (!$data['shops']): ?><p class="network-muted">Bắt đầu bằng hồ sơ cửa hàng. Bạn có thể gửi mẫu ngay sau đó; xuất bản sản phẩm cần hồ sơ shop đã duyệt.</p><?php endif; ?>
<?php foreach ($data['shops'] as $s): ?><div class="network-row"><div><strong><?=$escape($s['name'])?></strong><p><?=$escape($s['province'])?> · <?=$labels[$s['status']]?></p><?php if ($s['review_note']!==''): ?><p><?=$escape($s['review_note'])?></p><?php endif; ?></div><a href="shops.php?mode=merchant&amp;edit_shop=<?=$escape($s['id'])?>#shopForm">Chỉnh hồ sơ →</a></div><?php endforeach; ?>
<details id="shopForm" <?=!$data['shops']||$editingShop||($posted['action']??'')==='shop'?'open':''?>><summary><?=$editingShop?'Chỉnh hồ sơ cửa hàng':'Đăng ký cửa hàng'?></summary>
<form method="post" class="network-form"><input type="hidden" name="csrf" value="<?=$escape($auth->csrfToken())?>"><input type="hidden" name="action" value="shop"><input type="hidden" name="id" value="<?=$escape($shopValues['id']??App\Support\FashionNetwork::newId())?>"><input type="hidden" name="revision" value="<?=$escape($shopValues['revision']??0)?>">
<div class="network-fields"><?php $field('name','Tên cửa hàng',$shopValues,120,true); $field('province','Tỉnh / thành',$shopValues,120,true); $field('address','Địa chỉ công khai',$shopValues,300); $field('contact_url','Link liên hệ (website, Facebook, Zalo…)',$shopValues,2048,true,'url'); $field('website_url','Website cửa hàng · nếu có',$shopValues,2048,false,'url'); ?><label class="network-wide">Giới thiệu<textarea name="description" maxlength="2000" rows="3"><?=$escape($shopValues['description']??'')?></textarea></label></div><p class="network-muted">Chỉ nhập thông tin được phép công khai. Chỉnh hồ sơ đã xuất bản sẽ tạm ẩn hồ sơ và mẫu liên quan đến khi được duyệt lại.</p><button class="admin-button admin-button--solid">Gửi hồ sơ chờ duyệt</button>
</form></details></section>
<?php if ($data['shops']): ?>
<section class="network-panel"><h2>Mẫu sản phẩm</h2><p class="network-muted">Mỗi lần gửi là một mẫu màu/kích cỡ cụ thể. Chưa hỗ trợ tải tệp hoặc nhập hàng loạt; dùng link ảnh HTTPS mà bạn có quyền công bố.</p>
<?php foreach ($data['products'] as $p): ?><div class="network-row"><div><strong><?=$escape($p['name'])?></strong><p><?=$escape($shopNames[$p['shop_id']]??'')?> · <?=$labels[$p['status']]?></p><?php if ($p['review_note']!==''): ?><p><?=$escape($p['review_note'])?></p><?php endif; ?></div><a href="shops.php?mode=merchant&amp;edit_product=<?=$escape($p['id'])?>#productForm">Chỉnh mẫu →</a></div><?php endforeach; ?>
<details id="productForm" <?=$editingProduct||($posted['action']??'')==='product'||!$data['products']?'open':''?>><summary><?=$editingProduct?'Chỉnh mẫu sản phẩm':'Thêm mẫu sản phẩm'?></summary>
<form method="post" class="network-form"><input type="hidden" name="csrf" value="<?=$escape($auth->csrfToken())?>"><input type="hidden" name="action" value="product"><input type="hidden" name="id" value="<?=$escape($productValues['id']??App\Support\FashionNetwork::newId())?>"><input type="hidden" name="revision" value="<?=$escape($productValues['revision']??0)?>">
<div class="network-fields"><label>Cửa hàng<select name="shop_id" required><?php foreach ($data['shops'] as $s): ?><option value="<?=$escape($s['id'])?>" <?=$s['id']===($productValues['shop_id']??'')?'selected':''?>><?=$escape($s['name'])?></option><?php endforeach; ?></select></label><label>Loại Việt phục<select name="garment_id" required><option value="">Chọn loại áo</option><?php foreach ($garments as $g): ?><option value="<?=$escape($g['id'])?>" <?=$g['id']===($productValues['garment_id']??'')?'selected':''?>><?=$escape($g['name'])?></option><?php endforeach; ?></select></label>
<?php foreach (['name'=>['Tên sản phẩm',160,true],'variant_name'=>['Tên mẫu / biến thể',120,true],'color'=>['Màu thực tế',120,false],'material'=>['Chất liệu',200,false],'pattern'=>['Họa tiết / chi tiết',500,false],'sizes'=>['Kích cỡ',200,false],'included_accessories'=>['Phụ kiện kèm bộ · không gồm đồ tính riêng',500,false],'source_url'=>['Link sản phẩm nguồn',2048,true],'image_url'=>['Link ảnh mẫu HTTPS',2048,true]] as $key=>$spec) $field($key,$spec[0],$productValues,$spec[1],$spec[2],str_ends_with($key,'_url')?'url':'text'); ?>
<label class="network-wide">Mô tả thương mại · không dùng làm kết luận lịch sử<textarea name="description" rows="3" maxlength="3000"><?=$escape($productValues['description']??'')?></textarea></label></div>
<fieldset><legend>Dịch vụ & giá</legend><p class="network-muted">Để trống giá = liên hệ shop, không phải miễn phí. Ghi rõ giá một áo/cả bộ, thời gian thuê và phụ kiện tính riêng.</p>
<?php foreach ($offerLabels as $kind=>$label): ?><div class="network-offer-edit"><label class="network-check"><input type="checkbox" name="<?=$kind?>_enabled" value="yes" <?=($productValues[$kind.'_enabled']??'')==='yes'?'checked':''?>><?=$label?></label><div class="network-fields"><?php $field($kind.'_price','Giá tham khảo (VND)',$productValues,12); $field($kind.'_unit','Đơn vị giá · ví dụ: bộ / ngày',$productValues,80); if ($kind==='rent') $field('rent_deposit','Tiền cọc (VND)',$productValues,12); ?><label>Điều kiện / phụ kiện tính riêng<textarea name="<?=$kind?>_terms" rows="2" maxlength="1500"><?=$escape($productValues[$kind.'_terms']??'')?></textarea></label></div></div><?php endforeach; ?></fieldset>
<fieldset><legend>Quyền sử dụng ảnh</legend><label class="network-check"><input type="checkbox" name="display_consent" value="yes" required <?=($productValues['display_consent']??'')==='yes'?'checked':''?>>Tôi có quyền và cho phép V-Remix công bố ảnh này trong catalog.</label><label class="network-check"><input type="checkbox" name="ai_consent" value="yes" <?=($productValues['ai_consent']??'')==='yes'?'checked':''?>>Tôi có quyền và đề nghị cho phép gửi ảnh này sang dịch vụ AI để tạo bản phối. Đây là quyền riêng, không bắt buộc.</label><label>Căn cứ quyền sử dụng · chủ sở hữu, giấy phép hoặc liên kết xác nhận<textarea name="permission_evidence" required minlength="5" maxlength="1500" rows="3"><?=$escape($productValues['permission_evidence']??'')?></textarea></label><p class="network-muted">Thông tin căn cứ chỉ chủ shop và quản trị viên xem. Chọn quyền AI chưa tự gửi ảnh hoặc bật tạo ảnh từ sản phẩm này.</p></fieldset>
<p class="network-muted">Chỉnh mẫu đã xuất bản sẽ tạm ẩn mẫu đến khi được duyệt lại. Tình trạng sẵn có luôn cần liên hệ xác nhận.</p><button class="admin-button admin-button--solid">Gửi mẫu chờ duyệt</button>
</form></details></section>
<?php endif; ?>
